### PR TITLE
Changing the order to resolving env dependency

### PR DESCRIPTION
**Pull request by sammy17**

### CODE REVIEW

**Comment by dpetrisko** [comment]
Hi thanks for the PR. 

Did you see a problem without this change? ?= implies lazy evaluation in a Makefile, so the assignments won't get evaluated until they need to be i.e. after the chain is defined

**Comment by sammy17** [comment]
I see, somehow the flist.vcs was not generated without this change. Let me confirm this and get back to you.

**Comment by dpetrisko** [comment]
Can you also share your environment details?

**Comment by dpetrisko** [comment]
Closing, anyone feel free to reopen if they can reproduce

**Pull request closed without merging**
