### PR TITLE
Fix flist for verilator, vivado

### PR DESCRIPTION
**Pull request by Yuan-Mao**
PR #52 forgot to update the Makefile for verilator simulation. This PR adds back those updates. Now verilator can run properly.

### CODE REVIEW

**Comment by dpetrisko** [comment]
Probably need to update vivado/ as well then

**Comment by Yuan-Mao** [comment]
Okay let me figure out that before we merge.

**Comment by dpetrisko** [comment]
Thanks!

**Comment by Yuan-Mao** [comment]
Should be able to merge now.

**Comment by dpetrisko** [comment]
Thanks!

**Pull request merged**
