### PR TITLE
Adds peripheral support to zynq-parrot

### PR DESCRIPTION
**Pull request by dpetrisko**
This PR adds an external axilm to the zynq-parrot shell, enabling BP to communicate with generic Xilinx IP. To demonstrate this, a simple AXIL BRAM is added to the baseline black-parrot-example. To simplify the connections, individual axi clk/reset are replaced by a global clk/reset for the top module.

There's a bit of cleanup to do with adding assertions+comments, etc. but there's enough here to review

### CODE REVIEW

**Comment by Yuan-Mao** [comment]
I can confirm this PR can fix the stall issue on FPGA!

**Comment by Yuan-Mao** [comment]
https://github.com/black-parrot-hdk/zynq-parrot/blob/peripherals/cosim/black-parrot-example/ps.cpp#L258
Should we exclude this line when compiling ps.cpp in fpga/ ? I don't see axil_poll() defined for FPGA.

**Comment by dpetrisko** [comment]
Yeah you can
```
#ifndef FPGA
zpl->axil_poll()
#endif
```

That method is used to drive peripherals that we're emulating in the PL fabric that are external to the shell. On the FPGA, they're actually implemented so the PS doesn't have to do anything

**Comment by Yuan-Mao** [comment]
Thanks for the fix!

I just ran into another issue though: it seems to me with this peripheral support, the output got from the PL is not always complete. For example, when running prog.nbf, I always get "Hello Wo" and then the program exits normally. I have also tried running opensbi v1.0 + Linux kernel 5.15, and below is what I got:
Screenshot from 2022-01-10 10-06-12

... and this is what I got from Dromajo:

Screenshot from 2022-01-10 10-17-36

Seems like at least the data from PL is not coming out out-of-order, but it will drop somewhere somehow.

**Comment by dpetrisko** [comment]
Is this on FPGA or simulation?

**Comment by Yuan-Mao** [comment]
This is on FPGA. FPGA v.s. BP Dromajo

**Comment by dpetrisko** [comment]
Yep, I'm able to reproduce in FPGA

**Comment by dpetrisko** [comment]
I'm able to reproduce in cosim by this patch:
```
--- a/cosim/black-parrot-example/ps.cpp
+++ b/cosim/black-parrot-example/ps.cpp
@@ -260,6 +260,9 @@ extern "C" void cosim_main(char *argstr) {
 #ifndef FPGA
     zpl->axil_poll();
 #endif
+    for (int i = 0; i < 1000; i++)
+      get_counter_64(zpl, 0xA0000000 + 0x30bff8);
+
     // keep reading as long as there is data
     data = zpl->axil_read(0x10 + GP0_ADDR_BASE);
     if (data != 0) {
```
So it seems to be a back pressure issue.  I'll debug and get back to you

**Comment by Yuan-Mao** [comment]
Thank you so much Dan!

Maybe in the future we can also try adding random delay in our tests.

**Comment by dpetrisko** [comment]
Yes I think this is a great idea. I'll add a define for it so that sims can run with/without it

**Comment by dpetrisko** [comment]
I believe the issue should be fixed (at least hello world runs now). There was a minor issue in the configuration causing the interfaces not to line up. I also added flags for simulated backpressure to debug these types of issues in the future

**Comment by Yuan-Mao** [comment]
I can comfirm hello world runs now. However there seems to be some issues with my Linux kernel image. I will take care of that and do updates here if I find anything interesting.

**Comment by dpetrisko** [comment]
great thanks

**Comment by Yuan-Mao** [comment]
So after running hours of co-simulation, BP Dromajo and RTL get separate results during executing [this line](https://elixir.bootlin.com/linux/v5.15/source/arch/riscv/kernel/setup.c#L279). This happens to be the line that have puzzled me a lot for a while since the very beginning of my porting work for Linux 5.15. I have made [a patch](https://github.com/black-parrot-sdk/bp-linux/blob/b5468d6876a4422c0cd21e9c6c8ee43e3ca78438/cfg/linux.patch) about that line before in order to prevent kernel panic on Dromajo. However, seems like although Dromajo is now happy with the patch and will not generate a page fault on that line, RTL still does not buy it and will generate it instead.

So we kind of have two puzzles to solve here. The first one is to figure why we get different results here, and the second is whether we really need that patch. I have seen Qemu running well with kernel 5.15 without any patches. Maybe that would be a great starting point for the figuring out second issue.

**Comment by dpetrisko** [comment]
I would suggest running the kernel on unmodified dromajo. If the difference still exists with Qemu, we should raise an issue on the dromajo github. That could help pinpoint the area where things are diverging

**Comment by dpetrisko** [comment]
Merging this, since it fixes several outstanding issues and is only getting bigger

**Pull request merged**
