### PR TITLE
Bump BlackParrot and add backpressure to examples

### PR DESCRIPTION
**Pull request by dpetrisko**
This PR adds backpressure emulation to the examples, notably BlackParrot. This can act as a context switch on the PS, pressuring backwards on the system and triggering unusual contention patterns. One such bug was exposed in BP this way, so we're adding this hook to detect future bugs this way

### CODE REVIEW

**Comment by Yuan-Mao** [comment]
Nice! Maybe we would also want to add srand() to have deterministic simulation?

**Comment by dpetrisko** [comment]
Good idea!

**Comment by Yuan-Mao** [comment]
Looks like the fixes to BP do not solve all the issues. 

I ran my own Ethernet test program with the Ethernet peripheral and slow polling PS in simulation and I got the following result:

Screenshot 2023-02-22 at 12 52 50 PM

And again the simulation will run correctly if without slow polling. 

I will try to find a test case that can reproduce this on the master branch.

**Comment by dpetrisko** [comment]
I'm going to go ahead and merge this because I'm fairly sure the backpressure infrastructure itself is correct -- we can open new PRs for further bugs

**Pull request merged**
